"""Knowledge graph tool: query_knowledge_graph.

Loads a static JSON index of the SKiDL API (classes, methods, functions,
constants) and returns fuzzy-matched entries for a given query.
"""

from __future__ import annotations

import json
import logging
import os
from difflib import SequenceMatcher
from functools import lru_cache
from pathlib import Path
from typing import Any

log = logging.getLogger(__name__)

# KG_PATH env var lets you swap in a richer index (e.g. generated by
# introspecting the installed skidl package) without changing code.
_KG_PATH = Path(os.getenv("KG_PATH", Path(__file__).parent.parent / "data" / "skidl_kg.json"))

_TOP_K = 5


@lru_cache(maxsize=1)  # parse JSON once; survives the process lifetime
def _load_index() -> list[dict[str, Any]]:
    try:
        data = json.loads(_KG_PATH.read_text())
        log.info("Loaded KG index: %d entries from %s", len(data), _KG_PATH)
        return data
    except Exception as exc:
        log.error("Failed to load KG index from %s: %s", _KG_PATH, exc)
        return []


def _score(entry: dict[str, Any], query: str) -> float:
    """Score an entry against a query. Higher is better (0–1)."""
    q = query.lower()
    name = entry.get("name", "").lower()
    doc = entry.get("doc", "").lower()
    sig = entry.get("signature", "").lower()

    # Exact or prefix match in name gets a strong boost
    if q == name:
        return 1.0
    if name.startswith(q) or q in name:
        return 0.85

    # Check doc and signature for substring match
    if q in doc or q in sig:
        return 0.6

    # Word-level: any query word appears in name/doc/sig
    words = q.split()
    if words and any(w in name or w in doc for w in words if len(w) > 2):
        return 0.4

    # Fuzzy similarity on name as a last resort (scaled down to keep it
    # below the word-level tier even when the ratio is high).
    ratio = SequenceMatcher(None, q, name).ratio()
    if ratio > 0.5:
        return ratio * 0.5

    return 0.0


async def query_knowledge_graph(query: str, top_k: int = _TOP_K) -> str:
    """Look up SKiDL API structure (classes, methods, signatures) from the index.

    Returns a JSON string:
      {"matches": [{"name": "...", "type": "class|method|function", "signature": "...", "doc": "..."}, ...]}
    """
    log.info("query_knowledge_graph: %r", query)

    index = _load_index()
    if not index:
        return json.dumps({"matches": [], "error": "KG index not available"})

    scored = [(entry, _score(entry, query)) for entry in index]
    scored.sort(key=lambda x: x[1], reverse=True)

    matches = [
        {
            "name": e["name"],
            "type": e.get("type", "unknown"),
            "signature": e.get("signature", ""),
            "doc": e.get("doc", ""),
            **({"parent": e["parent"]} if "parent" in e else {}),
        }
        for e, score in scored[:top_k]
        if score > 0.0
    ]

    return json.dumps({"matches": matches})
